// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUZeUQnQXlgbytnTd24XBRLFBlME4xio',
    appId: '1:337409264740:web:f578287b7abee802362371',
    messagingSenderId: '337409264740',
    projectId: 'weather-8788b',
    authDomain: 'weather-8788b.firebaseapp.com',
    databaseURL: 'https://weather-8788b-default-rtdb.firebaseio.com',
    storageBucket: 'weather-8788b.firebasestorage.app',
    measurementId: 'G-8VG80EGNFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU-Sc5Gbq92HOZtLFHv2FU1oSbmJ6Clps',
    appId: '1:337409264740:android:bd2692fb81eeccf4362371',
    messagingSenderId: '337409264740',
    projectId: 'weather-8788b',
    databaseURL: 'https://weather-8788b-default-rtdb.firebaseio.com',
    storageBucket: 'weather-8788b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA89DEJ6ek7hrXkvT8CT-dAFdebe8S8tE',
    appId: '1:337409264740:ios:4a745fbf4c24fd73362371',
    messagingSenderId: '337409264740',
    projectId: 'weather-8788b',
    databaseURL: 'https://weather-8788b-default-rtdb.firebaseio.com',
    storageBucket: 'weather-8788b.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA89DEJ6ek7hrXkvT8CT-dAFdebe8S8tE',
    appId: '1:337409264740:ios:4a745fbf4c24fd73362371',
    messagingSenderId: '337409264740',
    projectId: 'weather-8788b',
    databaseURL: 'https://weather-8788b-default-rtdb.firebaseio.com',
    storageBucket: 'weather-8788b.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPUZeUQnQXlgbytnTd24XBRLFBlME4xio',
    appId: '1:337409264740:web:914f830be20455f5362371',
    messagingSenderId: '337409264740',
    projectId: 'weather-8788b',
    authDomain: 'weather-8788b.firebaseapp.com',
    databaseURL: 'https://weather-8788b-default-rtdb.firebaseio.com',
    storageBucket: 'weather-8788b.firebasestorage.app',
    measurementId: 'G-D8HFHCPBY3',
  );

}